name: projectunispiritfinalt
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  animated_theme_switcher: ^1.0.5
  cupertino_icons: ^1.0.2
  cloud_firestore: ^3.1.12
  firebase_core: ^1.14.1
  flutter_native_splash: ^2.1.6
  flutter_launcher_icons: ^0.9.2
  flutter_svg: ^1.0.3
  flutter_appauth: ^4.1.0+1
  flutter_secure_storage: ^5.0.2
  firebase_auth: ^3.3.14
  flutter_screenutil: ^1.0.2
  freezed_annotation: ^2.0.1
  firebase_messaging:
  http: ^0.13.4
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  fl_chart: ^0.36.2
  google_fonts: ^2.1.0
  google_sign_in:
  intl: ^0.17.0
  numberpicker:
  modal_progress_hud: ^0.1.3
#  line_awesome_flutter: ^1.0.1
  provider: ^5.0.0
  path_provider: ^2.0.2
  sqflite: ^2.0.0+3
  shared_preferences: ^2.0.13
  url_launcher: ^6.0.9
  connectivity_plus: ^2.3.5

dev_dependencies:
  build_runner: ^2.0.5

  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

  json_serializable: ^6.1.3

  freezed: ^2.0.2
  lint: any

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/meets/
